[*]
; reserve 1GB VRAM for mmproj file
fitt = 960
; minimum context length for useful work
fitc = 131072
; subagents run in parallel and share context
np = 1
; quantized kv cache is 30% faster
ctk = q8_0
ctv = q8_0
; flash attention reduces VRAM usage
fa = on
no-mmap = true
mlock = true
jinja = true

[Gemma4-26B-A4B]
model = E:\llama.cpp\gemma-4-26B-A4B\UD-Q6_K_XL.gguf
mmproj = E:\llama.cpp\gemma-4-26B-A4B\mmproj-BF16.gguf
; reduce system memory usage for cpu offloading
cram = 0
temp = 1.0
top-p = 0.95
top-k = 64

[Qwen3.6-27B]
load-on-startup = true
model = E:\llama.cpp\Qwen3.6-27B\UD-Q2_K_XL.gguf
mmproj = E:\llama.cpp\Qwen3.6-27B\mmproj-BF16.gguf
ctk = q4_0
ctv = q4_0
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"preserve_thinking": true}

[Qwen3.6-35B-A3B]
;load-on-startup = true
model = E:\llama.cpp\Qwen3.6-35B-A3B\UD-Q2_K_XL.gguf
mmproj = E:\llama.cpp\Qwen3.6-35B-A3B\mmproj-BF16.gguf
temp = 1.0
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"preserve_thinking": true}

[Qwen3.6-Coder]
;load-on-startup = true
model = E:\llama.cpp\Qwen3.6-35B-A3B\UD-Q2_K_XL.gguf
no-mmproj = true
; no need to reserve VRAM for vision encoder
fitt = 0
; 256k context length can support 2 subagents
np = 2
temp = 0.6
top-p = 0.95
top-k = 20
min-p = 0.0
presence-penalty = 0.0
repeat-penalty = 1.0
chat-template-kwargs = {"preserve_thinking": true}

[gpt-oss-20b]
model = E:\llama.cpp\gpt-oss-20b-mxfp4.gguf
; no need to reserve VRAM for mmproj
fitt = 0
; natively quantized to fp4
ctk = f16
ctv = f16
temp = 1.0
top-p = 1.0
chat-template-kwargs = {"reasoning_effort": "high"}
; grammar-file = E:\llama.cpp\no-native.txt
